# Generated by Django 5.0 on 2023-12-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('received_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contactus',
            },
        ),
    ]
