# Generated by Django 5.0 on 2023-12-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppontment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'BookAppontment',
            },
        ),
    ]
