# Generated by Django 5.0 on 2023-12-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='packages')),
                ('price', models.BigIntegerField()),
                ('includeds', models.TextField()),
            ],
        ),
    ]
