# Generated by Django 5.0 on 2023-12-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_packages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packages',
            table='Packages',
        ),
    ]
