# Generated by Django 5.0 on 2023-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('added_on', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Gallery',
            },
        ),
    ]
