# Generated by Django 5.0 on 2023-12-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='branches')),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('mon_sat', models.TimeField()),
                ('sun', models.TimeField()),
                ('maplink', models.TextField()),
            ],
        ),
    ]
