# Generated by Django 5.0 on 2023-12-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_branches'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branches',
            table='Branches',
        ),
    ]
