# Generated by Django 5.0 on 2023-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_branches_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='mon_sat',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='branches',
            name='sun',
            field=models.CharField(max_length=150),
        ),
    ]
