# Generated by Django 5.0 on 2023-12-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_branches_mon_sat_alter_branches_sun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
